spring:
  application:
    name: Blog

  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration-time: 3600000 # 1h in millisecond
  urls:
    auth:
      base: "/auth"
      login: "/login"
      signup: "/signup"
    post:
      base: "/api/posts"
      all : "/"
      add : "/"
      search : "/search"
    users:
      base: "/api/users"
      current-user: "/me"

